### ISSUE TITLE
Cannot combine allow/deny policies (set exceptions), RP falls back to default policy

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/requestpolicy#491]
Hi, I don't know if this is really a bug or something I don't understand about how RP works.

**How to reproduce:**
 * Default policy: deny
 * Go to some site that requests `ajax.googleapis.com` (eg. http://ouich.es/) and set RP to _Block all requests to *.ajax.googleapis.com_ (this domain is now marked as blocked everywhere - aka I don't trust this domain)
 * Go to http://www.commitlogsfromlastnight.com/, where `ajax.googleapis.com` is also required (now marked as blocked with the do-not-enter icon in RP menu)
 * Try to add an exception for this site (eg. I don't trust ajax.googleapis.com but allow it from this site) by clicking _Allow requests from *.commitlogsfromlast.com to *.ajax.googleapis.com_

**What happens:**
`ajax.googleapis.com` is still blocked from this domain (with a question mark), the only action available for it is now _Stop blocking requests to *.ajax.googleapis.com_.

**What's expected:**
requests to `ajax.googleapis.com` should be allowed from this domain (the new, domain-specific rule takes precedence over the global one set previously). The menu should display _stop allowing requests from *.commitlogsfromlastnight.com to *.ajax.googleapis.com_ in addition to the action that removes the global policy. (which does not apply from this domain since you've set an exception)

**Comment by shirishag75** [comment]
Thanx, just commenting here so I can follow the discussion as well.

**Comment by nodiscc** [comment]
@shirishag75 There is a `Subscribe` button on the right (commenting spams everyone subscribed to the repo). No harm done, just thought you should know.

**Comment by timkuijsten** [comment]
> Here is in what order (I think) rules should be processed (each rule overriding the previous one):

I like the general concept but I'm not sure if hard coding allow over deny is a good idea. Maybe a more [firewall rule like](http://www.openbsd.org/faq/pf/filter.html#defdeny) approach might be helpful here.
* parse rules from top to bottom.
* use most specific match (src, dst, domain/subdomain)
* use last (most specific) match
* maybe add the ability to skip further parsing of the rules (like the quick keyword in pf)

@nodiscc then your list might look something like:

* Default policy deny or allow
* Ship list of trackers, deny based on destination
* Ship list of subscriptions, allow based on origin and destinatation, allow sameorig
* User's deny/allow rules with only origin or destination (eg. Deny requests to *.untrusted.com)
* User's deny/allow rules for origin/destination pairs (eg. Allow requests from *.a.com to *.b.com)

**Comment by myrdd** [comment]
Thank you for your comment @timkuijsten!

---

> use most specific match (src, dst, domain/subdomain)

Yes, definitely. However, I'll give `* -> *.specific-domain.com` rules precedence over `*.specific-domain.com -> *` rules. When using RequestPolicy I simply think of destinations rather than origins. Here I've written down some cases:

Consider request `a -> b`, `a` and `b` being domain names.

* `a -> *`: deny; `* -> b`: deny
  * no conflict
* `a -> *`: allow; `* -> b`: allow
  * no conflict
* `a -> *`: deny; `* -> b`: allow
  * "allow" will get precedence
  * Default-allow: "allow" is desired
  * Default-deny: if you want to _deny_ `a -> *` you need to give that rule a higher priority
* `a -> *`: allow; `* -> b`: deny
  * "deny" will get precedence
  * Default-deny: "deny" is desired
  * Default-allow: if you want to _allow_ `a -> *` you need to give that rule a higher priority

---

> parse rules from top to bottom.
> use last (most specific) match

This only makes sense if ordering of rules is possible. However, I'd rather implement priority numbers.

Rules are currently stored in a JSON file, generated automatically. It's planned to order the rules in that file, having one rule per line – see #339.

If you want to be able to write your rules in a separate file, I could imagine different possibilities. See also #481.

> maybe add the ability to skip further parsing of the rules (like the quick keyword in pf)

I'd implement that as well with priority numbers. The rule with highest priority always wins.

---

> Ship list of trackers, deny based on destination
> Ship list of subscriptions, allow based on origin and destinatation, allow sameorig

The list of trackers is a subscription list as well. Currently all subscriptions have same priority.

**Comment by timkuijsten** [comment]
> * -> *.specific-domain.com rules precedence over *.specific-domain.com -> *

I'm not sure I find this logical, feels arbitrary to me. What about giving them the same precedence and let the rule with highest priority win?

**Comment by myrdd** [comment]
> What about giving them the same precedence and let the rule with highest priority win?

I guess you're right. That would be more explicit, which is actually good. However, I think the user should be informed about conflicting rules; there should be a message in the menu, maybe even an indicator on the icon/toolbarbutton, e.g. an exclamation mark.

Now, I think the most important feature we need right now is `a -> b` rules to have precedence over `a -> *` and `* -> b` rules. This is actually the purpose of this issue. I'll look into it to see if I can quickly implement this change.

**Comment by myrdd** [comment]
> I think the user should be informed about conflicting rules

See #752

The rule priorities issue is #717
