### ISSUE TITLE
Always show all available subscriptions in preferences

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/requestpolicy#529]
Adding https://github.com/RequestPolicyContinued/subscriptions/blob/master/official-deny_trackers.json as a subscription is not possible from chrome://requestpolicy/content/settings/subscriptions.html. This subscription has no entry/checkbox in the prefs.

**Comment by jstetten** [comment]
>As subscriptions override the default policy, enabling Block trackers is still useful in Default deny mode.

Just to chime in that this was exactly what I was expecting when I migrated to RPC. Seeing a bunch of pre-installed (-)'s in front of all the bad sites would be a much nicer user experience than having to manually go through the long list of (?)'s and deciding which to permanently ban or not.

A lot of work obviously went into deny_trackers.json. It would be great to be able to use this subscription while still staying in "default deny mode". (And seeing the resulting gray flag icon nodiscc mentioned would be a nice bonus!)

Great work so far! Let me know if I can be of help.

**Comment by myrdd** [comment]
I fully agree @jstetten. Milestone is the next release.

> Great work so far! Let me know if I can be of help.

I appreciate any kind of help! In this case you could investigate what needs to be changed, and create a patch. Multiple files need to be changed. If you [search for `Services.obs.notifyObservers(null, SUBSCRIPTION_ADDED_TOPIC, …)`](https://github.com/RequestPolicyContinued/requestpolicy/search?utf8=%E2%9C%93&q=notifyObservers+SUBSCRIPTION_ADDED_TOPIC&type=Code) you'll find good places to start. Contact me if you need help :)

**Comment by jstetten** [comment]
Thanks. I'm still trying to figure out your subscription service and how all the various settings files are generated.

For instance, in "Default deny" mode, my version of [subscriptions.html](https://github.com/RequestPolicyContinued/requestpolicy/blob/083f2172694af354d333729fbb3923a640b56753/src/content/settings/subscriptions.html#L59) has `data-defaultpolicy="allow"` instead of `data-defaultpolicy="deny"` at line 59, preventing the entire "Privacy" section from even displaying. Correct?

Also, in my own official subscriptions.json file, the `deny_trackers:{}` subscription never even existed to begin with, even though it [looks](https://github.com/RequestPolicyContinued/requestpolicy/blob/083f2172694af354d333729fbb3923a640b56753/src/content/lib/subscription.jsm#L101) like it should be there.

I need to investigate all this further.

**Comment by myrdd** [comment]
> For instance, in "Default deny" mode, my version of subscriptions.html has data-defaultpolicy="allow" instead of data-defaultpolicy="deny" at line 59, preventing the entire "Privacy" section from even displaying. Correct?

The `data-defaultpolicy` attribute serves as a selector, so to be exact, the attribute is passive. The attribute is used in [subscriptions.js](https://github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta10/src/content/settings/subscriptions.js). One part of fixing this issue is to always display all subscriptions. Anther part is *not to disable* any subscription when the default policy is changed.

> Also, in my own official subscriptions.json file, the deny_trackers:{} subscription never even existed to begin with, even though it looks like it should be there.

In default deny mode, `deny_trackers` is disabled, so it is never updated.

> I need to investigate all this further.

Do you want to be assigned to this issue?

**Comment by jstetten** [comment]
>The attribute is used in subscriptions.js

I see now. I also get that the .json file is only used for updating.

>Do you want to be assigned to this issue?

I'm not against it. Just know that the next two months is supposed to be a busy time for me in the real world. It will take me some time to start experimenting with how all the existing parts work together, as you said. I only just installed RPC a couple days ago.  :)

**Comment by myrdd** [comment]
Okay @jstetten, I see that only "collaborators" can be assigned to an issue, but you can work on it nevertheless. You'll have some weeks before beta11 is ready; so if you don't find the time, no worries.
