### ISSUE TITLE
Consolidate "Manage Policies" preferences pages into one

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/requestpolicy#558]
The current preferences have `Your policy`, `Default Policy` and `Subscriptions` as separated pages.
As it makes browsing the prefs more complex (_Where is that option? Is that one checked? click click click click) and the 2 first are actually very short, they should be consolidated in a single `Manage policies` page.

```
Default policy ----------------------------
 - [] Allow requests by default (help text)
 - [] Block requests by default (help text)
    - [] Allow requests to same domain (help text)

Subscriptions  ----------------------------
(help text)
 - [] Allow requests to .... (help text)
 - [] Allow requests to .... (help text)
 - [] Block requests to .... (help text)

Your policy  ----------------------------
Create rule
Policy:      [x] Block [ ] Allow
Origin:      [scheme     ] [host                   ] [port    ]
Destination: [scheme     ] [host                   ] [port    ]
Temporary:   [ ]
[Add rule]

Active rules
....
```

This has several advantages:
- Easier to navigate in the preferences
- Easier to get a global view of active policies
- Follows the logical order of which rules override the others (Your policy overrides Subscriptions which override Default Policy)

There are several bugs reported here that are caused by this UI confusing the users. I also find it confusing.

What do you think?

**Comment by grumpygeek** [comment]
Your policy should stay as a separate page but be renamed Your Rules because it has Create Rule and Active Rules (these are specific rules, not broad policies). Default and Subscription policies would be best combined on a single page/tab.  

Please also make sure a current Block policy isn't reset on update to Allow (can;t prove that it is, just seems like it is being reset sometimes).
