### ISSUE TITLE
Extension addons page, lastpass broken

### ISSUE THREAD

**Issue by Link-Satonaka** [RequestPolicyContinued/requestpolicy#572]
For many extensions, the options button will not work from about:addons while request policy 1.0beta8.1 is active.
This applies to a majority of my extensions. Try getting to the options from WOT or YARIP, for example.

When first enabling requestpolicy, the options buttons work, but they will cease to work upon restart until request policy is disabled.

**Comment by Link-Satonaka** [comment]
Requestpolicy is also responsible for breaking some of lastpass' dialogs (such as the ability to edit entries).

**Comment by myrdd** [comment]
Hi @Link-Satonaka 

- **WOT:** I guess you mean [Web of Trust](https://addons.mozilla.org/en-US/firefox/addon/wot-safe-browsing-tool/), no? Clicking on *Preferences* on `about:addons` works for me. It opens a new tab.
- **YARIP:** You mean [Yet Another Remove It Permanently](https://addons.mozilla.org/en-US/firefox/addon/yarip/). Same as with WOT, clicking on *Preferences* on `about:addons` works for me. It opens a window instead of a tab though.

There are two possibilities for you:
- test the two addons together with RP in a new profile.
- see what is logged by RP when clicking "preferences" is blocked. See those instructions: https://github.com/RequestPolicyContinued/requestpolicy/wiki/Setting-up-a-development-environment#enable-logging

For **lastpass** having a look at the logging might help as well.

**Comment by Link-Satonaka** [comment]
I forgot to put this in the video, but the request log shows nothing.
In the browser console, this error appears when clicking "Options"

`ReferenceError: rpService is not defined - frame.dom-content-loaded.js:248`

Nothing appears in stderr with loglevel 0 when pressing "Options".

A video: http://1drv.ms/1sHy6ds

**Comment by Link-Satonaka** [comment]
I recompiled the latest beta from github (I'm using the dev-restartless-and-e10s branch if the version number doesn't imply that) and I no longer have this problem, however there is a new problem.

"Allow requests to the same domain (www.example.com -> static.example.com)."
The option does nothing now- it is effectively off regardless of what I check

**Comment by myrdd** [comment]
Ah I see you used the `dev-restartless-and-e10s` branch. It was quite buggy, that's right. Please tell me that the next time you've got a problem on a dev branch.
