### ISSUE TITLE
Summary of requested UI changes

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/requestpolicy#601]
As discussed in https://github.com/RequestPolicyContinued/requestpolicy/issues/517#issuecomment-63688808 here is a quick draft of what added UI elements could look like, if added as requested in:
- 1.0 block/allow list needs visual outline box #360 
-  Visual indicator for temporary rules in the menu #167 
-  option to quickly switch default policy #495 
-  Change wording for "Disable blocking/Enable blocking" in menu #497 
-  Add temporary permisions to whitelist #294 
-  Feature Request: Quick Link to WOT or other Safety Search #456 
-  Display "Temporary" actions in italic + light green/red #517 
-  Pre filled rule creation #470 
-  REQUEST: one-time approval click #422 

![rp-ui](https://cloud.githubusercontent.com/assets/3950390/6203350/8bea801e-b51d-11e4-8d00-7bbd9125ee83.png)

This could help getting a clearer view of what the menu UI could look like. I omitted  "bundle" rules #338  as there is already a screenshot there. I'll upload a screenshot without annotations if needed, feedback welcome.

I forgot the visual indicator for private browsing mode (https://github.com/RequestPolicyContinued/requestpolicy/issues/261 - temporary rules only). Having FF's "private browsing" icon on bottom right with text `Private browsing. Only temporary rules allowed` should do it.

**Comment by Cerberus-tm** [comment]
This is all *very* good, well done!

One more thing: I'd like to be able to individually make temporary rules permanent too, perhaps by right-clicking a temporary rule?

I'd also like to e.g. allow all subdomains on .cloudfront, instead of xsdkfljd.cloudfront or uyxwiuet.cloudfront, etc. (sometimes the same site uses several cloudfront subdomains). But that is probably already solved by your edit button next to the rule? I wouldn't mind clicking that button, then being sent to the rule-editing screen, then removing "xsdkfljd" to get that.

**Comment by nodiscc** [comment]
>  I'd like to be able to individually make temporary rules permanent too, perhaps by right-clicking a temporary rule?

Please discuss in #294. The `Make permanent` button would make all current temporary rules permanent. Making just one of these rules permanent is not planned.

> 'd also like to e.g. allow all subdomains on .cloudfront, instead of xsdkfljd.cloudfront or uyxwiuet.cloudfront, etc. 

Please discuss in #470. The edit button would show a dialog with a pre-filled rule you can edit:  
`[Allow]` requests from `[*]` to `[*.gravatar.com] [OK] [Cancel]`

**Comment by Cerberus-tm** [comment]
I've added my comment to issue number 294. Rarely would I want to make all temporary permissions permanent: nearly always I only want to make one or two permanent. Perhaps this depends on the kinds of sites you visit, but especially with complex sites this would save me a lot of time. As it is, I have to reload the site twice in order to make a single permission permanent. The workflow in the OP's second post on issue number 294 is exactly what I do all the time.

That is great! That should work for all possible scenarios.

**Comment by myrdd** [comment]
Thanks a lot @nodiscc for putting it all together, it will help me a lot. Thumbs up!
I've added the `wanted` label to this issue, because those changes will improve the menu a lot!

**Comment by Cerberus-tm** [comment]
Yay, this will be great! Especially being able to make temporary permissions permanent one by one will help me.

**Comment by netjeff** [comment]
I'd really appreciate options to disable or switch default policies **only for the current tab**.   Like "Disable blocking **on this tab**" or "Switch default policy **on this tab**".  This would be very similar to #422, but the timeliness would be for the life of the current tab rather than the options discussed on #422.

Here's my use case:  I run with "default deny".  Many times I'll have a tab open on a site that I'm unlikely to come back to (or else rarely), but I need to buy something or maybe fill out a support form.  Even with the "temporarily allow all from ThisSite.com", due to 3rd party request (especially for credit cards) even that doesn't work.  Usually I'm willing to take a bit of risk for convenience, and use the "disable blocking" option.  But that puts me at risk in all my other tabs, plus I have to remember to undisable after I'm done.  So having a "disable blocking **for this tab**" (or maybe switch default policy for this tab) would limit the risk only to that one tab.

I'm not sure how to fit this onto an already crowded menu... maybe a checkbox next to the switch, labelled something like "this tab only" ?

**Comment by Cerberus-tm** [comment]
@netjeff Excellent idea, I would use this! I often experience the same scenario.

**Comment by tim-teufel** [comment]
:+1: 
Also, we would want some warning from RPC about that carte blanche tab. Maybe, a _crossed_ flag?

**Comment by myrdd** [comment]
I agree, I also would like that feature ;) There's already an issue about it. I've posted my comment there: #495
