### ISSUE TITLE
"Allow requests to the same domain" doesn't apply to 3rd party resources

### ISSUE THREAD

**Issue by Whissi** [RequestPolicyContinued/requestpolicy#602]
Hi,

steps to reproduce:
1. In RequestPolicy prefs go to *Default policy* and enable **Allow requests to the same domain**
2. Make sure you have an active rule allowing `*.github.com <> *.githubusercontent.com`
3. Now go to https://github.com/RequestPolicyContinued/requestpolicy/compare/RequestPolicy:dev-1.0...dev-1.0

You will see that content from *render.githubusercontent.com* isn't allow to load content from *raw.githubusercontent.com*.

Tested with 1.0.beta8.2.

**Comment by nodiscc** [comment]
Hi @Whissi, this is because RP Continued uses the [Public Suffix List](https://publicsuffix.org/list/effective_tld_names.dat) as a way to determine what a top-level domain is. You can see in the list that `githubusercontent.com` is a top level domain, like `.com` is. So `render.githubusercontent.com` and `raw.githubusercontent.com` are actually _not_ the same domain.

You can learn more about the Public Suffix List at http://en.wikipedia.org/wiki/Public_Suffix_List and https://publicsuffix.org/

Does this answer your question?

**Comment by Whissi** [comment]
Yup, you answered my question. Thank you!
