### ISSUE TITLE
update license headers in source files

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#607]
There has been some discussion – #578 – about the copyright lines in the source files' headers. Currently it's only me and justin in there, and the years do not represent in which years that specific file has been worked on.

This issue therefore includes:
- [x] discuss / establish rules about how the copyright lines in GPL-licensed files should look like
- [ ] change the license headers as they are now to conform the rules.

Some thoughts about the copyright lines:
- I think that only _significant_ contributions should be represented by the copyright lines. What means "significant" sometimes needs to be discussed in the specific cases.
- IMO the years mentioned in each file's header should mean: „In that year there have been 'significant' contributions to that file.“ So if a file hasn't been changed in one year, that year shouldn't be mentioned at all.
- I've found [this article](http://softwarefreedom.org/resources/2007/originality-requirements.html) titled _„Originality Requirements under U.S. and E.U. Copyright Law“_, it might be an interesting lecture.

**Comment by nodiscc** [comment]
> only significant contributions should be represented by the copyright lines

http://stackoverflow.com/a/3487102/1054728 says: _You should add the current year to the list of copyright years if and only if you make a copyrightable change to the file. Trivial patches like adding null pointer checks and the like are generally considered to not be copyrightable_

So a significant change is something that involves creative thought. Renaming variable or adding trivial comments is not considered copyrightable.

http://stackoverflow.com/a/20911485/1054728 says: _Google doesn't update their copyright dates because they don't care whether some page they started in 1999 and updated this year falls into the public domain in 2094 or 2109. And if they don't, why should you?_

I tend to agree with this. Don't bother updating copyright years.

> how the copyright lines in GPL-licensed files should look like

I think including the standard short GPLv3 header is fine:

```
Copyright (C) 2015  whoami <who@ami.org>

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option)
any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
more details.

You should have received a copy of the GNU General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>.

```

**Comment by myrdd** [comment]
> So a significant change is something that involves creative thought.

This wording seems good.

> Don't bother updating copyright years.

Okay, so regarding copyright updating the years isn't necessary. However, I think it would be at least nice if the years were updated, because then you can quickly see who did when (approximately) contribute to that file. This is also what is written in [this article](https://www.softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html):

> (…) each time a contributor modifies a file significantly, his or her copyright notice should be added to the top of the file. *If a notice for that developer already exists, it should be updated as necessary to reflect the year the new contribution was made.* (…)
>
> Well-maintained file-scope copyright notices make it possible to tell at a glance which developers made modifications to a given file. This eases the task of auditing the code in the case of an authorship dispute and can provide useful evidence in license enforcement actions. If a file is used separately from the rest of the codebase, its authors can still be clearly identified.

Of course using `git log` instead would safe us maintaing the years up to date – which is discussed in that article afterwards. So in fact *not* updating would be OK for me. What do you think @nodiscc?

One more thing: The copyright lines should be ordered by the year of each contributor's first contribution, no? So in many files it would be first Justin, then me.

**Comment by nodiscc** [comment]
> not updating would be OK for me [...] then you can quickly see who did when (approximately) contribute to that file

It is ok to update years. It is also ok not to do so, because git commit logs should be enough should a copyright dispute arise. It is important to list all contributors for each file. However if you want trackability/attribution for specific commits, then git logs are the way to go. So, no big deal if the years are inexact/lagging behind real ones.

**Comment by myrdd** [comment]
Alright, I think I won't update the years. So we can now step over to actually apply what we've decided. I'd do that when https://github.com/RequestPolicyContinued/requestpolicy/issues/489 is merged.
