### ISSUE TITLE
Flash/plugins requests are not filtered

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/requestpolicy#636]
This is a long-standing limitation and is even described on the website. RPC is not able to filter requests from plugins such as Flash, SIlverlight, Java... As nothing can be done about it (@myrdd why? they don't go through [nslContentPolicy](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIContentPolicy) ?), I suggest adding switches to the advanced prefs dialog to disable those plugins. 

This kind of solution was accepted by @mydd for WebRTC https://github.com/RequestPolicyContinued/requestpolicy/issues/586:

> That would disable WebRTC in general. If there is no other way, RP should encourage to disable WebRTC.

Adding the `important` label on purpose because it's clearly a limitation of RequestPolicy Continued, and filtering fails silently. The current workaround (expecting users to read the doc and manually disable plugins) is not good enough in my humble opinion.

Related to https://github.com/RequestPolicyContinued/requestpolicy/issues/628 because this issue is about adding a switch to the advanced preferences dialog.

**Comment by myrdd** [comment]
> RPC is not able to filter requests from plugins (...) why?

In fact I've never checked that, but I'm quite sure it's because Plugins run in their own process. So I guess Firefox could just prevent *invoking* the plugins.

> they don't go through nslContentPolicy ?

Not sure. There's a type constant called `TYPE_OBJECT_SUBREQUEST`. MDN says it *„indicates a request by a plugin“*. I would have to look into it.

More info about Plugins on the [MDN article](https://developer.mozilla.org/en-US/Add-ons/Plugins).

**Comment by nodiscc** [comment]
NPAPI plugins are not supported anymore, fixed.
