### ISSUE TITLE
Firefox 38 broke RequestPolicy 0.5

### ISSUE THREAD

**Issue by dcarosone** [RequestPolicyContinued/requestpolicy#661]
The original RP has stopped working for me with the new firefox.  Presumably also for many others.

I have just discovered this project, and the status of the original, as a result.  Presumably, so will others.

No pressure, but this seems like a good time and good opportunity for a release...

This issue is mostly to alert (and attract searches) that there's likely to be an increase in demand for a released version in the normal mozilla addons pages.

**Comment by nodiscc** [comment]
Hi @dcarosone the latest beta is available at https://requestpolicycontinued.github.io/.

If you want to keep using the unmaintained 0.5x version, there is a Firefox 38+ compatible version at Firefox 38+ https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/ (check https://github.com/RequestPolicyContinued/requestpolicy/issues/643#issuecomment-104455268)

Uploading RequestPolicy Continued to addons.mozilla.org is planned in https://github.com/RequestPolicyContinued/requestpolicy/issues/543

Does this help?

**Comment by myrdd** [comment]
@dcarosone as *nodiscc* said, there's the stable release on AMO ([0.5.29](https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/)), which is simply a fork of the old addon. You can't find it in the AMO search because it's still awaiting review by the AMO team, but you can install it nevertheless.

@nodiscc shouldn't we put a link to the 0.5.29 release prominently on our website (https://requestpolicycontinued.github.io/)? I think it's time to do that.

**Comment by dcarosone** [comment]
Thanks, I'm now running the beta. The issue wasn't so much about my case
personally, as about getting the project ready for the pending influx.

A prominent link to the 38+ version would be a great idea, as I hadn't seen
that option. AMO approval would help, but perhaps be a mixed blessing, as I
would probably have never realised it was unmaintained in that case.

**Comment by myrdd** [comment]
> getting the project ready for the pending influx

Yeah, in fact we know it already for many months. We even pushed back the "incompatibility" from Fx36 to Fx38. See #525. However, what we did *not* expect is that Firefox disables the addon automatically (!) on upgrade.

> A prominent link to the 38+ version would be a great idea, as I hadn't seen that option.

I think it's best if we put a link both on the [website](https://requestpolicycontinued.github.io/) and this [repo's readme](https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/README.md). On the website there will be *two* buttons then.

Waiting for @nodiscc's answer, he's maintaining the website.

**Comment by dcarosone** [comment]
Sorry, yes, I didn't mean the project internally, I meant discoverability for new users.

And let me just say, after using the beta for a few hours -- 

__OMG THIS IS SOOO MUCH NICER!!__ *Well done.*

**Comment by myrdd** [comment]
@dcarosone credits to the new menu largely goes to justin, the former developer and creator of RP.

closing this issue as soon as RP 0.5 is referenced on the website, and eventually on the readme.

**Comment by nodiscc** [comment]
I've added the AMO link for the 0.5 addon with extended compatibility: https://github.com/nodiscc/rp-website/wiki#-about-requestpolicycontinued (this wiki's contents will be [mirrored to the website](https://github.com/RequestPolicyContinued/requestpolicy/issues/445#issuecomment-97158054) as soon as I have a build script - hopefully this week)

**Comment by myrdd** [comment]
Thank you @nodiscc. However, I would rather add a *button* (instead of just a link in some chapter). It could be for example like in the following screenshot, the color of the Beta button could be different though.

![buttons](https://cloud.githubusercontent.com/assets/4286829/7886799/b76abf6e-062c-11e5-85a3-4516b3bd187e.jpg)

The code for those two buttons would be:

```
| [ [[_media/addtofirefox.png]]](https://github.com/RequestPolicyContinued/requestpolicy/releases/download/v1.0.beta9.3/requestpolicy-1-0-beta9-3.xpi) <br />stable release | [ [[_media/addtofirefox.png]]](https://github.com/RequestPolicyContinued/requestpolicy/releases/download/v1.0.beta9.3/requestpolicy-1-0-beta9-3.xpi) <br /> beta release |
| --------- | --------------- |
```

Don't you think it would be better to promote the 0.5 version?

**Comment by nodiscc** [comment]
Right, I'll add this button.

> Don't you think it would be better to promote the 0.5 version?

I don't know. The 0.5 version is useful for people who don't want to upgrade to 1.xbeta for various reasons (no context menu, unable to migrate rules - though I guess this is mostly solved?), but it is stable in the sense _no future bug fixes, no new features/enhancements, no ongoing development_. I think it would be better to get users to install the beta (1.x) as it brings more relevant testing/feedback for the addon.

Your work on 1.x has made it _really_ better! Don't you think it would be great to get new and existing users to use it?

IMHO using the extended compatibility 0.5 version should be a fallback.

**Comment by myrdd** [comment]
Thanks for your opinion! I'm still very uncertain about how to decide, but I tend to agree to you. Anyone who has been a 0.5 user and misses something from the features that aren't in 1.0 yet will find RPC's 0.5 version. Any new users could install 1.0 without problems.

So another possible solution would be to make the 0.5 download button smaller (but green), and the 1.0 bigger (but orange, or red, or yellow).
We could even „subtitle“ the buttons with a small font size. The texts could be:
„0.5 is the latest stable release“ and
„1.0 is being actively developed, but due to some [compatibility issues](https://github.com/RequestPolicyContinued/requestpolicy/issues?q=is%3Aopen+is%3Aissue+label%3A%221.0+vs+0.5%22) some users might not want to upgrade yet “

Any other opinions are welcome!

**Comment by dcarosone** [comment]
I like the simple language of the subtitles, giving some guidance on how to
choose.

But instead of 'latest stable release', call 0.5 something like 'old
version repackaged for current Firefox'.

For me, the lack of deny rules in the old version was already making me
frustrated and look (unsuccessfully) for an alternative. Don't
underestimate the number of users willing to try a better version beta,
rather than minimal change.

**Comment by dcarosone** [comment]
Another small point: the opportunity to clean up my rules collection by
just not importing it, and getting a better ui to make the next one, was
welcome. Not everyone will want to be forced to do it right now, but it's
something else to consider.

Links to screenshots and tutorials about how to do rules management well in
the new RP will sway many in this direction too.

**Comment by DJ-Leith** [comment]
**dcarosone** said:
> This issue is mostly to alert (and attract searches) that there's likely to be an increase in demand for a released version in the normal mozilla addons pages.

I agree the important issue is to keep 'those on Fx Release' using RP/RPC until 1.x.x is ready.

**myrdd** said:
> Yeah, in fact we know it already for many months. We even pushed back the "incompatibility" from Fx36 to Fx38. See #525. However, what we did *not* expect is that Firefox disables the addon automatically (!) on upgrade.

I hope the MANDATORY signing of addons (#600) will not be another gotcha.

**nodiscc** said:
> Your work on 1.x has made it *really* better! Don't you think it would be great to get new and existing users to use it?

I agree! (to both sentences)

**dcarosone** said:
> But instead of 'latest stable release', call 0.5 something like 'old version repackaged for current Firefox'.

and

> Links to screenshots and tutorials about how to do rules management well in the new RP will sway many in this direction too.

Yes, to both of these points.

**Comment by myrdd** [comment]
Thank you for your supportive words! I think the solution with the two buttons with subtitles is the way to go.
@nodiscc what's the current plan? If you get the new website ready in the next few days, it's ok to keep the old website's button as it is, but if it takes longer, then I would prefer to have the current website's download buttons adjusted. You know what I mean?
If you don't have time, I'm sure someone could make a pull request for the current website.

---

#### Reply to @dcarosone's comments:

> call 0.5 something like 'old version repackaged for current Firefox'.

Yes, that sounds better.

@nodiscc so this will be the 0.5 subtitle, and the 1.0 subtitle will be *„1.0 is being actively developed, but due to some [compatibility issues](https://github.com/RequestPolicyContinued/requestpolicy/issues?q=is%3Aopen+is%3Aissue+label%3A%221.0+vs+0.5%22) some users might not want to upgrade yet“*

> Another small point: the opportunity to clean up my rules collection by just not importing it, and getting a better ui to make the next one, was welcome.

I don't know what you mean exactly @dcarosone. Do you mean you like the „Your policy“ preferences page (`about:requestpolicy?yourpolicy`)?

> Links to screenshots and tutorials about how to do rules management well in the new RP will sway many in this direction too.

There will be [this future Quick Start](https://github.com/nodiscc/rp-website/wiki/quickstart.md).
@dcarosone It would be great if you could take a look at it – especially if you already know what you would expect – and write a comment on issue #445 about that page.

---

#### Reply to @DJ-Leith's comment:

> I hope the MANDATORY signing of addons (#600) will not be another gotcha.

I hope that, too; but I think with my current plan (see my post on that issue) it will be a smooth transition at least for 1.0 users.

**Comment by myrdd** [comment]
> ~~@nodiscc what's the current plan? If you get the new website ready in the next few days, it's ok to keep the old website's button as it is, but if it takes longer, then I would prefer to have the current website's download buttons adjusted. You know what I mean?~~
> ~~If you don't have time, I'm sure someone could make a pull request for the current website.~~

Wait @nodiscc, I've messed it up, forget it. The current website https://requestpolicycontinued.github.io/ emphasizes the 1.0 version, and that's what we want.
Still, on the new website I'd like to see two buttons.
Thank you for your work @nodiscc!

**Comment by nodiscc** [comment]
Thank you both for your help; closing this issue to only have 1 tracking bug for the website, please check https://github.com/RequestPolicyContinued/requestpolicy/issues/445#issuecomment-107389133
