### ISSUE TITLE
Malfunctions with local Web applications

### ISSUE THREAD

**Issue by 0nse** [RequestPolicyContinued/requestpolicy#759]
**How to reproduce**?

Access a locally running Web application (for me, it's [mopidy-mopify](https://github.com/dirkgroenen/mopidy-mopify) and [spotmop](https://github.com/jaedb/spotmop)) that tries to access external domains. It does not matter whether I access it via `127.0.0.1:6680` or my machine's hostname.

I'm using RequestPolicy Continued `1.0.beta11pre4.1436.rb482daa` and Firefox `44.0` on Linux.

---

**What is the expected behaviour?**

The regular RequestPolicy Continued behaviour.

---

**What is the observed behaviour?**

![xxx](https://cloud.githubusercontent.com/assets/7449611/12720311/79af946a-c8fa-11e5-8d0d-962ced6a0db3.png)

* The allow-options appear twice for all external requests.
* Allowing from `127.0.0.1` to `127.0.0.1` (or from `127.0.0.1` to `fonts.googleapis.com` ) and reloading will no longer show the option (as is correct)  but will still not allow requests
* Manually entering these rules in the preferences has the same effect.
* Temporarily allowing all requests to this resource will work.

---

Maybe the port is the problem?

**Comment by myrdd** [comment]
Hi @0nse 

Yes, the problem here is that the menu does not support custom ports yet. For that, please follow #473. The solution is to create the rules manually. Keep in mind you need to set the "port" value in your case; you can use `*` as well. I'd suggest you to allow `127.0.0.1:* -> 127.0.0.1:*`, as well as `127.0.0.1:* -> fonts.googleapis.com` or whatever you need.

> The allow-options appear twice for all external requests.

I don't know why that is happening. To further understand I'd need to see your request log, especially the "pre-paths" [1]. However, in any case #473 should be solved first, so I'm closing this issue as a duplicate.

[1] https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIURI#Components_of_a_URI

BTW thanks for the detailed report :)

**Comment by 0nse** [comment]
Thanks. You've solved my problem. The request log tells me that the duplicates are due to requests to the same address but with different protocols:
```
http://127.0.0.1:6699/mopify/ -> http://127.0.0.1:6699/mopify/assets/webfonts/ss-standard.css
http://127.0.0.1:6699/mopify/ -> ws://127.0.0.1:6699/mopify/queuemanager/
```

Your linked issue talks about this so I will not open a new one.

**Comment by myrdd** [comment]
I see. In this case you need another rule, specifying the "ws" scheme plus the "6699" port. Of course you can also use the wildcard/asterisk `*`.
So the duplicate entry in the menu could come from the "ws" scheme.
