### ISSUE TITLE
Request Log: open and close with keyboard key.

### ISSUE THREAD

**Issue by gineadai** [RequestPolicyContinued/requestpolicy#778]
It's was unconventional to open request log in context menu of version 0.5 and now even more when you need drag mouse all over the screen from right click menu to menu in the corner.

Like sidebar key in AdblockPlus.

**Comment by gineadai** [comment]
And I hope you make classic menu someday, not just link.

**Comment by myrdd** [comment]
Thanks for your suggestion. What do you think should be the keyboard shortcut for opening the request log? The shortcut for the menu is `alt+shift+R`.

> And I hope you make classic menu someday, not just link.

see #662

**Comment by gineadai** [comment]
Can you add entry in about:config where you can set custom shortcut?
Like `extensions.adblockplus.filters_key` 
And default one may be `ctrl+shift+x` or `alt+shift+z` i am not sure.

**Comment by myrdd** [comment]
I guess for now the default combo for now will be none.

Since this very easy to implement, I could slot this task in as the next task. However, I don't know when I'll do it in fact. Would you like to create a pull request for that? I could mentor you. The change should be very easy modifying these files:

* https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/src/content/controllers/keyboard-shortcuts.jsm
* https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/src/content/lib/default-preferences.js

However, the `KeyboardShortcut` class currently requires a default combo, so you'd need to modify that one as well:

* https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/src/content/lib/classes/keyboard-shortcut.jsm

Tell me if you'd like to work on it. :)

**Comment by myrdd** [comment]
@gineadai please try the latest version:
https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/versions/1.0.beta11.1.1484.r5124b50.pre

documentation in the FAQ:
https://github.com/RequestPolicyContinued/requestpolicy/wiki/FAQ#how-do-i-configure-requestpolicys-keyboard-shortcuts

**Comment by gineadai** [comment]
Not work. Browser console show `TypeError: window.rpcontinued is undefined`.

**Comment by myrdd** [comment]
@gineadai please provide some details. Which Browser / Version are you using? Could you try it in a new browser profile? A screenshot might help as well.

**Comment by gineadai** [comment]
@myrdd Never mind. Now it work.
