### ISSUE TITLE
Redirect "Add Rule" should also execute allow action

### ISSUE THREAD

**Issue by kkeane** [RequestPolicyContinued/requestpolicy#808]
When a page redirects, RP will offer three options "Allow" "Deny" and "Add Rule" The third option will end up denying the redirect even if you want it allowed. It will also sometimes add the wrong rule (I reported this as a separate issue #809 ).

One site where this problem is extensively noticeable is http://www.codeproject.com/script/News/List.aspx
1. Clear any RP rules related to codeproject.com
2. Visit the Web site http://www.codeproject.com/script/News/List.aspx
3. Click on one of the story links
4. Note that RP offers "Allow" "Deny" and "Add Rule"
5. Select "Add Rule"
6. Select "Allow from codeproject.com to xxx.com"
7. Expected result: rule is added, and user is taken to xxx.com
8. Actual result: rule is added, but user remains on codeproject.com. You have to click on the original link a second time to actually go to the site.

Note: in some cases, such as checkout from an online merchant, the problem is even more serious because it may force you to click "submit" twice or something along those lines.

**Comment by myrdd** [comment]
You're right, adding an allow-rule should redirect to the target url.

The “more” button was re-introduced in commit https://github.com/RequestPolicyContinued/requestpolicy/commit/48364cd7583d3539a1550689b014a47d9c624a5b. To fix this issue, [`overlay._showRedirectNotification`](https://github.com/RequestPolicyContinued/requestpolicy/blob/1d2cd54c763ac3d3c73a45c7da6ce94a3c050832/src/content/ui/overlay.js#L385) and [`classicmenu.js`](https://github.com/RequestPolicyContinued/requestpolicy/blob/1d2cd54c763ac3d3c73a45c7da6ce94a3c050832/src/content/ui/classicmenu.js) need to be modified. More or less, [this anonymous function](https://github.com/RequestPolicyContinued/requestpolicy/blob/1d2cd54c763ac3d3c73a45c7da6ce94a3c050832/src/content/ui/overlay.js#L482) should be called instead of [this simple reload](https://github.com/RequestPolicyContinued/requestpolicy/blob/1d2cd54c763ac3d3c73a45c7da6ce94a3c050832/src/content/ui/classicmenu.js#L49). Fixing this issue should be fairly easy.

**Comment by myrdd** [comment]
https://github.com/RequestPolicyContinued/requestpolicy/commit/45c210d8a4a2fb1fce8b8ef72e299d77c4dcabc3 solves this issue
