### ISSUE TITLE
WE transition: Implement "fake" `browser.runtime.getURL()` function

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/requestpolicy#865]
* The function should be put [here](https://github.com/RequestPolicyContinued/requestpolicy/blob/489ddf49eb1f218518080a53feae1a64fcddc833/src/conditional/legacy/content/web-extension-fake-api/models/api.js#L248).
* The function should map `/paths/to/files.ext`:
  * Map `/content/settings/(\w+).html` (regexp) to `about:requestpolicy?{filenameWithoutExt}`
  * Prepend everything else with `chrome://rpcontinued`, so `getUrl("/content/foo/bar.css")` will give 
~~`chrome://rpcontinued/foo/bar.css`~~ `chrome://rpcontinued/content/foo/bar.css`.

**Comment by jrrdev** [comment]
Quick question about the expected behaviour when the function must prepend with `chrome://rpcontinued` : 
- `getUrl("/content/foo/bar.css")` should return : 
    - `chrome://rpcontinued/content/foo/bar.css` (no change in the path)
    - or `chrome://rpcontinued/foo/bar.css` as you said ?

For instance [here](https://github.com/RequestPolicyContinued/requestpolicy/blob/489ddf49eb1f218518080a53feae1a64fcddc833/src/content/lib/utils/strings.js#L35) the URL is `chrome://rpcontinued/locale/requestpolicy.properties` and I'm guessing this will become `browser.runtime.getURL("/locale/requestpolicy.properties"` (relative path to manifest.json and I believe this file must be in root directory in WE)

**Comment by myrdd** [comment]
Ah, my mistake! … "no change in the path" is the way to go. We need the `content/` part.

> For instance here the URL is chrome://rpcontinued/locale/requestpolicy.properties and I'm guessing this will become browser.runtime.getURL("/locale/requestpolicy.properties")

`browser.runtime.getURL()` will only be used for html pages in the `content/` directory. The locale ecosystem needs to be changed for the WE version.
